project_name: baralga
builds:
- env: [CGO_ENABLED=0]
  goos:
  - linux
  goarch:
  - amd64
  - arm64
dockers:
- image_templates: ["ghcr.io/baralga/baralga-app:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/amd64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/baralga/baralga-app
  - --label=org.opencontainers.image.source=https://github.com/baralga/baralga-app
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
- image_templates: ["ghcr.io/baralga/baralga-app:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64/v8
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/baralga/baralga-app
  - --label=org.opencontainers.image.source=https://github.com/baralga/baralga-app
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
- name_template: ghcr.io/baralga/baralga-app:{{ .Version }}
  image_templates:
  - ghcr.io/baralga/baralga-app:{{ .Version }}-amd64
  - ghcr.io/baralga/baralga-app:{{ .Version }}-arm64v8
- name_template: ghcr.io/baralga/baralga-app:latest
  image_templates:
  - ghcr.io/baralga/baralga-app:{{ .Version }}-amd64
  - ghcr.io/baralga/baralga-app:{{ .Version }}-arm64v8
changelog:
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    # Commit messages matching the regexp listed here will be removed from the changelog
    exclude:
      - '^docs:'
      - '^misc:'
      - typo
      - (?i)foo