version: '3'
services:

  db_postgres:
    image: postgres:17
    container_name: baralga___db
    hostname: db_postgres
    environment:
      - "POSTGRES_DB=baralga"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports: 
      - "5432:5432"
