name: build-docker

on:
  push:
    tags:
      - '*'
    branches:
      - feature/mvp
      
permissions:
  contents: write

jobs:
  build-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up Go cover
        working-directory: api
        run: go get golang.org/x/tools/cmd/cover
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: api
      - name: Test
        working-directory: api
        run: make test
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          workdir: api
          args: release --snapshot --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}