name: build-docker

on:
  workflow_call:

jobs:
  build-code:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Set up Go cover
        working-directory: .
        run: go get golang.org/x/tools/cmd/cover
      - name: Set up arch-go
        working-directory: .
        run: make arch-go.install
      - name: Run arch-go check
        working-directory: .
        run: make arch-go.check
      - name: Test
        working-directory: .
        run: make test
