name: build-docker

on:
  workflow_call:

jobs:
  build-code:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: go.mod
      - name: Set up Go cover
        working-directory: .
        run: go get golang.org/x/tools/cmd/cover
      - name: Set up arch-go
        working-directory: .
        run: make arch-go.install
      - name: Run arch-go check
        working-directory: .
        run: make arch-go.check
      - name: Test
        working-directory: .
        run: make test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: go.mod
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          args: --timeout=5m