name: api-deploy-gcloud

on:
  push:
    branches:
      - main
      - feature/mvp
      
permissions:
  contents: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Generate app.yaml
        working-directory: api
        run: make app.yaml
        env:
          BARALGA_DB: ${{ secrets.BARALGA_DB }}
          BARALGA_JWTSECRET: ${{ secrets.BARALGA_JWTSECRET }}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
        working-directory: web
      - run: npm run build
        working-directory: web
      - name: Deploy api + web
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy api/app.yaml web/app.yaml --quiet