name: deploy-gcloud

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-code:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy:
    needs: build-code
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v5
        with:
          go-version-file: go.mod
      - name: Generate app.yaml
        working-directory: .
        run: make app.yaml
        env:
          BARALGA_DB: ${{ secrets.BARALGA_DB }}
          BARALGA_DBMAXCONNS: ${{ secrets.BARALGA_DBMAXCONNS }}
          BARALGA_JWTSECRET: ${{ secrets.BARALGA_JWTSECRET }}
          BARALGA_CSRFSECRET: ${{ secrets.BARALGA_CSRFSECRET }}
          BARALGA_SMTPSERVERNAME: ${{ secrets.BARALGA_SMTPSERVERNAME }}
          BARALGA_SMTPFROM: ${{ secrets.BARALGA_SMTPFROM }}
          BARALGA_SMTPUSER: ${{ secrets.BARALGA_SMTPUSER }}
          BARALGA_SMTPPASSWORD: ${{ secrets.BARALGA_SMTPPASSWORD }}
          BARALGA_DATAPROTECTIONURL: ${{ secrets.BARALGA_DATAPROTECTIONURL }}
          BARALGA_GITHUBCLIENTID: ${{ secrets.BARALGA_GITHUBCLIENTID }}
          BARALGA_GITHUBCLIENTSECRET: ${{ secrets.BARALGA_GITHUBCLIENTSECRET }}
          BARALGA_GITHUBREDIRECTURL: ${{ secrets.BARALGA_GITHUBREDIRECTURL }}
          BARALGA_GOOGLECLIENTID: ${{ secrets.BARALGA_GOOGLECLIENTID }}
          BARALGA_GOOGLECLIENTSECRET: ${{ secrets.BARALGA_GOOGLECLIENTSECRET }}
          BARALGA_GOOGLEREDIRECTURL: ${{ secrets.BARALGA_GOOGLEREDIRECTURL }}
          BARALGA_WEBROOT: ${{ secrets.BARALGA_WEBROOT }}
      - name: Deploy
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.GCLOUD_PROJECT_ID}}
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml dispatch.yaml --quiet
