name: build-docker

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:
  build-code:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  build-docker:
    needs: build-code
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 0
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          workdir: .
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}