name: build-docker

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write

jobs:
  build-code:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  build-docker:
    needs: build-code
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          workdir: .
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}